name: YoPayment
version: '${project.version}'
main: com.noloverme.yopayment.YoPaymentPlugin
api-version: '1.16'
authors:
  - noloverme
description: Создание ссылок для оплаты через ЮKassa

softdepend:
  - PlaceholderAPI

# Команды плагина
commands:
  yopayment:
    description: Основная команда плагина YoPayment
    usage: /yopayment <create|reload|list> [аргументы]
    aliases:
      - yp
      - yopay
    permission: yopayment.use

# Разрешения
permissions:
  yopayment.use:
    description: Основное разрешение на использование плагина
    default: false

  yopayment.create:
    description: Создание платёжных ссылок для себя
    default: op
    parent: yopayment.use

  yopayment.create.others:
    description: Создание платёжных ссылок для других игроков
    default: op
    parent: yopayment.create

  yopayment.reload:
    description: Перезагрузка конфигурации плагина
    default: op
    parent: yopayment.use

  yopayment.list:
    description: Просмотр списка активных платежей
    default: op
    parent: yopayment.use

  yopayment.list.others:
    description: Просмотр покупок других игроков
    default: op
    parent: yopayment.list

libraries:
  - com.zaxxer:HikariCP:7.0.2
  - com.h2database:h2:2.4.240
  - com.mysql:mysql-connector-j:9.7.0
  - org.postgresql:postgresql:42.7.11
  - com.google.code.gson:gson:2.14.0